name:                advent-of-code
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- base >= 4.7 && < 5
#- containers
#- text
#- mtl
#- stm
#- split


library:
  source-dirs: src

tests:
  advent-of-code-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code
    - hspec
